# Generated by Django 4.1.6 on 2023-03-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_product_adder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='turkmentelekechi',
            name='emails',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default='product'),
        ),
    ]
