# Generated by Django 4.1.6 on 2023-03-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_forgotpassord_turkmentelekechi_emails_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForgotPassord',
            new_name='ForgotPassword',
        ),
    ]
