# Generated by Django 4.1.6 on 2023-03-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
