# Generated by Django 4.1.6 on 2023-04-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
